AllCops:
  Exclude:
    - db/schema.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2
Layout/AlignArray:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4
Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4
Layout/IndentFirstArrayElement:
  Enabled: false
Layout/IndentFirstHashElement:
  Enabled: false
Layout/IndentFirstArgument:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets
Style/SymbolArray:
  EnforcedStyle: brackets
Style/NumericPredicate:
  EnforcedStyle: comparison
Style/ZeroLengthPredicate:
  Enabled: false
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
